# Karabiner-Elements configuration (macOS only)
#
# Configuration is managed by karabiner.ts (TypeScript).
# Build: cd karabiner-config && deno run --allow-env --allow-read --allow-write karabiner.ts
#
# This module only ensures the config directory exists.
# The actual karabiner.json is generated by karabiner.ts.
{
  pkgs,
  lib,
  config,
  ...
}: let
  inherit (pkgs.stdenv) isDarwin;
in {
  # Ensure karabiner config directory exists (macOS only)
  home.activation.ensureKarabinerDir = lib.mkIf isDarwin (
    lib.hm.dag.entryAfter ["writeBoundary"] ''
      $DRY_RUN_CMD mkdir -p "${config.home.homeDirectory}/.config/karabiner"
    ''
  );
}
