---@type vim.lsp.Config
return {
  filetypes = {
    'astro',
    'css',
    'eruby',
    'haml',
    'html',
    'htmlangular',
    'heex',
    'javascript',
    'javascriptreact',
    'less',
    'liquid',
    'markdown',
    'php',
    'sass',
    'scss',
    'stylus',
    'svelte',
    'twig',
    'typescript',
    'typescriptreact',
    'vue',
  },
  settings = {
    tailwindCSS = {
      files = {
        exclude = {
          '**/.git/**',
          '**/node_modules/**',
          '**/.venv/**',
          '**/venv/**',
          '**/__pycache__/**',
          '**/dist/**',
          '**/build/**',
          '**/target/**',
          '**/result/**',
          '**/.next/**',
          '**/.nuxt/**',
          '**/coverage/**',
          '**/.cache/**',
        },
      },
    },
  },
}
